baseURL = 'http://trswnca.cc/'
languageCode = 'en-us'
title = "trswnca's\nNotebook"
theme = 'diary'
buildDrafts = false

[[module.mounts]]
    source = '../obsidian-files/'
    excludeFiles = ['/thoughts/**', '/templates/**', '/diary/**', '/bibtex/**']
    target = 'content'

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 2

[params]
subtitle = "知足且上进\n温柔且坚定"
enableLaTeX = true
# enableReadingTime = true

[[menu.main]]
url = "/notebook"
name = "技术笔记"
weight = 3

[[menu.main]]
url = "/papers"
name = "论文笔记"
weight = 2

[[menu.main]]
url = "/tags"
name = "标签分类"
weight = 100


